exclude: "config/exclude.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config.json"
description: "config/description.md"

min_date: 1950
min_length: 10000
root: "min_dev"

mask:
  from_beginning: 7000
  from_end: 2000
