name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    uses: nextstrain/.github/.github/workflows/pathogen-repo-ci.yaml@master
    with:
      env: |
        NEXTSTRAIN_DOCKER_IMAGE: nextstrain/base:branch-nextalign-v2
